#!/bin/bash
# Parameters:
# 1: Module Name - defaults to this this project
# {{ Change this line when building a new Joomla Module:
PROJECT=${1:-auctionaffiliate}
# }}

if [[ ! -d mod_$PROJECT ]] ; then
  echo "Can't find the mod_$PROJECT directory"
  exit 1
fi

VERSION=$( grep "<version>"  mod_$PROJECT/mod_$PROJECT.xml  | sed -e "s/\s*<version>\(.*\)<\/version>.*/\1/")

if [[ -z $VERSION ]]; then
  printf "The <version>-tag is not defined in file mod_%s/mod_%s.xml\n" $PROJECT $PROJECT
  exit 1
fi

printf "Building module mod_%s version %s...\n" $PROJECT $VERSION

printf "  Removing cruft first...\n"
find . -name "*~" -exec rm -f {} \;  -print

[[ ! -d .build ]] && mkdir -p .build


printf "  Building zip package mod_%s_%s.zip in the .build directory...\n" ${PROJECT} ${VERSION}
[[ -f .build/mod_${PROJECT}_${VERSION}.zip ]] && rm -f .build/mod_${PROJECT}_${VERSION}.zip
zip -r .build/mod_${PROJECT}_${VERSION}.zip mod_${PROJECT} -x mod_${PROJECT}/.\* > /dev/null

printf "  Building zip package mod_%s_%s.tar.gz in the .build directory...\n" ${PROJECT} ${VERSION}
[[ -f .build/mod_${PROJECT}_${VERSION}.tar.gz ]] && rm -f .build/mod_${PROJECT}_${VERSION}.tar.gz
tar -czvf .build/mod_${PROJECT}_${VERSION}.tar.gz  --exclude='.*' --exclude='*~' mod_${PROJECT} > /dev/null

printf "Done\n"
