#!/bin/bash
# $Id: build 50 2013-11-17 15:00:32Z gerrit_hoekstra $
# Parameters:
# 1: Module Name - defaults to this this project
# {{ Change this line when building a new Joomla Module:
PROJECT=${1:-auctionaffiliate}
# }}

if [[ ! -d mod_$PROJECT ]] ; then
  echo "Can't find the mod_$PROJECT directory"
  exit 1
fi

VERSION=$( grep "<version>"  mod_$PROJECT/mod_$PROJECT.xml  | sed -e "s/\s*<version>\(.*\)<\/version>.*/\1/")

if [[ -z $VERSION ]]; then
  printf "The <version>-tag is not defined in file mod_%s/mod_%s.xml\n" $PROJECT $PROJECT
  exit 1
fi

printf "Building module mod_%s version %s...\n" $PROJECT $VERSION

printf "  Removing cruft...\n"
find . -name "*~" -exec rm -f {} \;  -print

printf "  Building zip package...\n"
[[ -f mod_${PROJECT}_${VERSION}.zip ]] && rm -f mod_${PROJECT}_${VERSION}.zip
zip -r mod_${PROJECT}_${VERSION}.zip mod_${PROJECT} -x mod_${PROJECT}/.\*

printf "  Building tar.gz package...\n"
[[ -f mod_${PROJECT}_${VERSION}.tar.gz ]] && rm -f mod_${PROJECT}_${VERSION}.tar.gz
tar -czvf mod_${PROJECT}_${VERSION}.tar.gz  --exclude='.*' --exclude='*~' mod_${PROJECT}

printf "Done\n"
